// The icons a module can have in the sidebar. A module stores only the icon's NAME (the key below);
// the sidebar, the Module Master table and the icon picker all turn that name into a picture from here,
// so whatever the picker offers can always be drawn.
import {
  Activity,
  Award,
  BadgeCheck,
  BarChart3,
  Banknote,
  Bell,
  BookOpen,
  Boxes,
  Briefcase,
  Building2,
  Calendar,
  CheckCircle,
  ClipboardList,
  Clock,
  CreditCard,
  Database,
  Download,
  FilePlus,
  FileText,
  Folder,
  Gauge,
  Gift,
  Globe,
  HandCoins,
  Heart,
  Home,
  IdCard,
  Image,
  IndianRupee,
  Key,
  Landmark,
  Layers,
  LayoutDashboard,
  LayoutGrid,
  LineChart,
  Link as LinkIcon,
  List,
  ListChecks,
  Lock,
  Mail,
  Map,
  MapPin,
  Megaphone,
  MessageCircle,
  MessageSquare,
  Newspaper,
  Package,
  PieChart,
  Phone,
  Printer,
  Receipt,
  Search,
  Settings,
  Shield,
  ShieldCheck,
  Star,
  Store,
  Table,
  Tag,
  Truck,
  Upload,
  User,
  UserCheck,
  UserCog,
  UserPlus,
  Users,
  UserX,
  Wallet,
  Wrench,
} from 'lucide-react';

// name -> icon, in the order the picker shows them (the first ones are what this panel already uses)
export const MENU_ICONS = {
  'layout-dashboard': LayoutDashboard,
  'layout-grid': LayoutGrid,
  gauge: Gauge,
  home: Home,
  layers: Layers,
  users: Users,
  user: User,
  'user-check': UserCheck,
  'user-plus': UserPlus,
  'user-cog': UserCog,
  'user-x': UserX,
  'id-card': IdCard,
  building: Building2,
  briefcase: Briefcase,
  landmark: Landmark,
  store: Store,
  database: Database,
  list: List,
  'list-checks': ListChecks,
  'clipboard-list': ClipboardList,
  'file-text': FileText,
  'file-plus': FilePlus,
  folder: Folder,
  'book-open': BookOpen,
  newspaper: Newspaper,
  receipt: Receipt,
  'credit-card': CreditCard,
  wallet: Wallet,
  banknote: Banknote,
  'indian-rupee': IndianRupee,
  'hand-coins': HandCoins,
  badge: BadgeCheck,
  tag: Tag,
  'bar-chart': BarChart3,
  'pie-chart': PieChart,
  'line-chart': LineChart,
  activity: Activity,
  table: Table,
  map: Map,
  'map-pin': MapPin,
  globe: Globe,
  calendar: Calendar,
  clock: Clock,
  link: LinkIcon,
  bell: Bell,
  mail: Mail,
  phone: Phone,
  megaphone: Megaphone,
  'message-square': MessageSquare,
  'message-circle': MessageCircle,
  shield: Shield,
  'shield-check': ShieldCheck,
  key: Key,
  lock: Lock,
  'check-circle': CheckCircle,
  settings: Settings,
  wrench: Wrench,
  search: Search,
  upload: Upload,
  download: Download,
  printer: Printer,
  star: Star,
  heart: Heart,
  award: Award,
  gift: Gift,
  truck: Truck,
  package: Package,
  boxes: Boxes,
  image: Image,
};

export const MENU_ICON_NAMES = Object.keys(MENU_ICONS);
